name: Code Quality

on:
  pull_request:

jobs:
  cq:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.18'

      - name: Install
        run: yarn install

      - name: PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: echo "$PR_TITLE" | yarn commitlint

      - name: Lint
        run: yarn lint
