name: lerna publish

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          fetch-depth: 0
          node-version: '16.18'

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Configure Git User
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "@$GITHUB_ACTOR"

      - name: "NPM Identity"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

      - name: "Publish"
        run: |
          npx lerna publish from-package --conventional-commits --no-verify-access --yes

      - name: "Examples"
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/examples/dist
