name: Publish

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          fetch-depth: 0
          node-version: '16.18'

      - name: Pull all tags for Lerna semantic release
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Ensure access
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Config git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Bump versions and publish packages
        run: yarn publish:ci

      - name: Put examples on gh-page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/examples/dist

      - name: Create Doc
        run: yarn doc

      - name: Push Doc
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs(root): update docs"
