name: Tests

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.18'

      - name: Install
        run: yarn install

      - name: Test
        run: yarn test --coverage

#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v2
#        with:
#          name: ref-lcov.info
#          path: ./coverage/lcov.info
#
#      - name: Generate Code Coverage report
#        id: code-coverage
#        uses: barecheck/code-coverage-action@v1
#        with:
#          barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
#          lcov-file: "./coverage/lcov.info"
#          base-lcov-file: "./coverage/lcov.info"
#          minimum-ratio: 0 # Fails Github action once code coverage is decreasing
#          send-summary-comment: true
#          show-annotations: "warning" # Possible options warning|error
